DROP TABLE IF EXISTS tds;
DROP TABLE IF EXISTS hydration;

CREATE TABLE tds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tds INTEGER NOT NULL
);

CREATE TABLE hydration (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  differ INTEGER NOT NULL,
  current_vol INTEGER NOT NULL
);

INSERT INTO hydration (created, differ, current_vol)
    VALUES ('2022-1-1 12:00:00 +0900', 0, 0)